[[headers]]
  for = "/magic"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
    CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/magic/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
    CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/magic/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
    CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Netlify-CDN-Cache-Control = "public, max-age=31536000, immutable"
    CDN-Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
    CDN-Cache-Control = "public, max-age=86400, stale-while-revalidate=604800"
